config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: :registrations }
  
  root "static_pages#show"
  
  resources :users, only: [:index, :show] do
    resources :reviews, except: :index
  end
  resources :books, only: [:index, :show] do
    resources :rates, only: [:create]
    resource :suggest_books, only: :create
  end
  resources :reviews do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :authors, only: [:index, :show]
  resources :categories, only: [:show]
  resources :comments
  get "users/:id/reviews" => "users#reviews", as: :user_all_reviews
  resources :relationships, only: [:create, :destroy]
  get "search", to: "static_pages#index", as: :search
  get "users/:id/followers", to: "users#followers", as: :user_followers
  get "users/:id/following", to: "users#following", as: :user_following
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]
  
  has_many :reviews
  has_many :comments, dependent: :destroy
  has_many :rates
  
  validate :validate_username
  validates :name, presence: true

  mount_uploader :image, AvatarUploader
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
  
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
  # tinh tong so like user nhan duoc
  def count_getted_like
    user = User.find_by id: self.id
    reviews = user.reviews
    total = 0
    reviews.each do |review|
      total += review.count_like
    end
    return total
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  
  def show
    per_page = params[:page]
    @reviews = @user.reviews.order(created_at: :desc).page(per_page).per 4
  end
  
  def reviews
    @reviews = @user.reviews.order(created_at: :desc)
      .page(params[:page]).per(10)
  end
  
  def following
    per_page = params[:page]
    @user  = User.find(params[:id])
    @users = @user.following.page(per_page).per 10
  end

  def followers
    per_page = params[:page]
    @user  = User.find(params[:id])
    @users = @user.followers.page(per_page).per 10
  end
  
  private

  def find_user
    @user = User.find_by id: params[:id]

    return if @user.present?
    flash[:danger] = "User not found"
    redirect_to root_path
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary follow-button" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_review.html.erb
<div class="toggle-overflow item row">
  <div class="image col-sm-4 col-md-3">
    <div class="row">
      <%= link_to user_review_path(review.user, review),
        data: {turbolinks: false} do %>
        <% if review.photos.any? %>
          <%= image_tag review.photos.first.url %>
        <% else %>
          <%#<%= image_tag review.book.picture %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="content col-sm-8 col-md-9">
    <h3 class="title-font user-review-title">
      <%= link_to review_path(review), data: {turbolinks: false} do %>
        <%= review.book.title %>
      <% end %>
    </h3>
    <p class="user-review-title"><b><%= review.title %></b></p>
    <div class="details">
      <span>
        <%= t "reviews.index.reviewer" %>
        <%= link_to review.user.name, user_path(review.user),
          data: {turbolinks: false} %>&emsp;|&emsp;
      </span>
      <span class="glyphicon glyphicon-time"></span>
      <span title="<%= review.created_at.to_s %>">
        <%= review.created_at.strftime("%d %b %Y") %>
      </span>&emsp;|&emsp;
      <span class="fa fa-comments fa-md"></span>
      <%= review.comments.count %>&emsp;|&emsp;
      <span class="fa fa-thumbs-o-up"></span>
      <%= review.likes.count %>
    </div>
    <p class="row more">
      <%= truncate_html(review.content, length: 350, omission: ' ...') %>
    </p>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
  html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn unfollow-button" %>
<% end %>

app/views/users/followers.html.erb
<div class="user-followers">
  <h1>
    <%= link_to user_path(@user) do %>
      <%= @user.name %>
    <% end %>
    &gt; Followers
  </h1><hr><br>

  <% @users.each do |user| %>
    <div class="row follower">
      <div class="col-sm-2">
        <div class="follower-image">
          <%= link_to user_path(user) do %>
            <img alt="<%= user.name %>" src="<%= user.try :image %>">
          <% end %>
        </div>
      </div>
      <div class="col-sm-5">
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %><br>
        <span><%= user.reviews.count %> reviews</span> |
        <span><%= user.rates.count %> rating</span><br>
      </div>
      <div class="col-sm-5 text-right">

      </div>
    </div>
  <% end %>
</div>

app/views/users/following.html.erb
<div class="user-followers">
  <h1>
    <%= link_to user_path(@user) do %>
      <%= @user.name %>
    <% end %>
    &gt; Followings
  </h1><hr><br>

  <% @users.each do |user| %>
    <div class="row follower">
      <div class="col-sm-2">
        <div class="follower-image">
          <%= link_to user_path(user) do %>
            <img alt="<%= user.name %>" src="<%= user.try :image %>">
          <% end %>
        </div>
      </div>
      <div class="col-sm-5">
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %><br>
        <span><%= user.reviews.count %> reviews</span> |
        <span><%= user.rates.count %> rating</span><br>
      </div>
      <div class="col-sm-5 text-right">

      </div>
    </div>
  <% end %>
</div>

app/views/users/reviews.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4 col-sm-4">

      <div class="card hovercard">
        <div class="cardheader">

        </div>
        <div class="avatar">
          <%= image_tag @user.image.to_s %>
        </div><br>
        <div class="info">
            <div class="title">
                <a target="_blank" href="https://scripteden.com/"><%= @user.name %></a>
            </div>
            <div class="desc"><%= @user.username %></div>
            <div class="desc">Email: <%= @user.email %></div>
            <!--<div class="desc">Birth: <= @user.birth %></div>-->
        </div>
        <% if user_signed_in? && @user.id == current_user.id %>
          <div class="text-center profile-buttons">
            <%= link_to "Edit", edit_user_registration_path, method: :get,
              class: "btn btn-primary btn-sm", data: {turbolinks: false} %>
          </div>
        <% end %><br>

      </div>
    </div>
    
    <div class="col-lg-8 col-sm-8">
      <div class="profile-content">
        <div class="widget article userLists">
          <h2><%= t "users.show.reviews_title" %><%= @user.username %></h2>
          <div id="list-reviews">
            <div class="text-center" data-turbolinks="false">
              <div class="review-pagination">
                <%= paginate @reviews %>
              </div>
              <!--<p class="page-info"><= page_entries_info @reviews %></p>-->
            </div><hr>
            <div class="reviews">
              <% if @reviews.any? %>
                <% @reviews.each do |review| %>
                  <%= render partial: "review", locals: {review: review} %>
                  <div class="edit-review text-right">
                    <% if user_signed_in? && @user.id == current_user.id %>
                      <%= link_to t("button.edit"), edit_user_review_path(current_user, review),
                        class: "btn btn-success", data: {turbolinks: false} %>
                      <%= link_to t("button.delete"), user_review_path(current_user, review),
                        method: :delete, data: {confirm: t("button.confirm"), turbolinks: false},
                        class: "btn btn-danger" %>
                    <% end %>
                  </div><hr>
                <% end %>
              <% else %>
                <% if user_signed_in? && current_user.id == @user.id %>
                  <%= t "users.show.no_review" %>
                <% end %>
              <% end %>
            </div>
            <div class="review-pagination text-center" data-turbolinks="false">
              <%= paginate @reviews %>
            </div>
          </div>
        </div>
      </div>
    </div>

	</div>
</div>

app/views/users/show.html.erb
<div class="user-page">
	<div class="row">
		<div class="col-lg-4 col-sm-4">

      <div class="card hovercard">
        <div class="cardheader">

        </div>
        <div class="avatar">
          <%= image_tag @user.image.to_s %>
        </div><br>
        <div class="info">
          <div class="title">
            <a target="_blank" href="https://scripteden.com/"><%= @user.name %></a>
          </div>
          <div class="desc"><%= @user.username %></div>
          <div class="desc">Email: <%= @user.email %></div>
          <!--<div class="desc">Birth: <= @user.birth %></div>-->
          <div class="desc">
            Reviews: <%= @user.reviews.count %>
          </div>
          <div class="desc">
            Following:
            <a href="<%= user_following_path(@user) %>"> 
              <strong id="following" class="stat">
                <%= @user.following.count %>
              </strong>
            </a>
          </div>
          <div class="desc">
            Followers: 
            <a href="<%= user_followers_path(@user) %>">
              <strong id="followers" class="stat">
                <%= @user.followers.count %>
              </strong>
            </a>
          </div>
        </div>
        <% if user_signed_in? %>
          <% if @user.id == current_user.id %>
            <div class="text-center profile-buttons">
              <%= link_to "Edit", edit_user_registration_path, method: :get,
                class: "btn btn-primary btn-sm", data: {turbolinks: false} %>
            </div>
          <% else %>
            <div id="follow_form" style="margin-top: 20px;">
              <% if current_user.following?(@user) %>
                <%= render 'unfollow' %>
              <% else %>
                <%= render 'follow' %>
              <% end %>
            </div>
          <% end %>
        <% end %><br>
        
        <!--<div class="bigBox">-->
        <!--  < if @user.followers.any? %>-->
        <!--    <div class="h2Container gradientHeaderContainer">-->
        <!--      <h2 class="brownBackground">-->
        <!--        <= link_to user_followers_path(@user) do %>-->
        <!--          <= @user.name %>'s Followers (<= @user.followers.size.to_s %>)-->
        <!--        < end %>-->
        <!--      </h2>-->
        <!--    </div>-->
        <!--    <div class="bigBoxBody">-->
        <!--      <div class="bigBoxContent containerWithHeaderContent">-->
        <!--        < @user.followers.limit(12).each do |follower| %>-->
        <!--          <div>-->
        <!--            <= link_to user_path(follower), class:"leftAlignedImage" do %>-->
        <!--              <img alt="<= follower.name %>" src="<= follower.try :image %>"-->
        <!--                title="<= follower.name %>">-->
        <!--            < end %>-->
        <!--          </div>-->
        <!--        < end %>-->
        <!--      </div>-->
        <!--    </div>-->
        <!--  < end %>-->
        <!--</div>-->

      </div>
    </div>

    <div class="col-lg-8 col-sm-8">
      <div class="profile-content">
        <div class="widget article userLists">
          <h2><%= @user.name %>'s reviews</h2>
          <hr>
          <div id="list-reviews">
            <div class="text-center" data-turbolinks="false">
              <div class="review-pagination">
                <%= paginate @reviews %>
              </div>
              <!--<p class="page-info"><= page_entries_info @reviews %></p>-->
            </div>
            <div class="reviews">
              <% if @reviews.any? %>
                <% @reviews.each do |review| %>
                  <%= render partial: "review", locals: {review: review} %>
                  <div class="edit-review text-right">
                    <% if user_signed_in? && @user.id == current_user.id %>
                      <%= link_to t("button.edit"), edit_user_review_path(current_user, review),
                        class: "btn btn-success", data: {turbolinks: false} %>
                      <%= link_to t("button.delete"), user_review_path(current_user, review),
                        method: :delete, data: {confirm: t("button.confirm"), turbolinks: false},
                        class: "btn btn-danger" %>
                    <% end %>
                  </div><hr>
                <% end %>
              <% else %>
                <% if user_signed_in? && current_user.id == @user.id %>
                  <%= t "users.show.no_review" %>
                <% end %>
              <% end %>
            </div>
            <div class="review-pagination text-center" data-turbolinks="false">
              <%= paginate @reviews %>
            </div>
          </div>
        </div>
      </div>
    </div>

	</div>
</div>