config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: :registrations }
  
  root "static_pages#show"
  
  resources :users, only: [:index, :show] do
    resources :reviews, except: :index
  end
  resources :books, only: [:index, :show] do
    resources :rates, only: [:create]
    resource :suggest_books, only: :create
  end
  resources :reviews do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :authors, only: [:index, :show]
  resources :categories, only: [:show]
  resources :comments
  get "users/:id/reviews" => "users#reviews", as: :user_all_reviews
  resources :relationships, only: [:create, :destroy]
  get "search", to: "static_pages#index", as: :search
  get "users/:id/followers", to: "users#followers", as: :user_followers
  get "users/:id/following", to: "users#following", as: :user_following
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :load_support

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    @review.user_id = current_user.id
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:user_id, :title, :content, :book_id)
  end
  
  def load_support
    @support = Supports::Reviews.new review: Review.all, param: params
  end
end

app/views/reviews/_form.html.erb
<%= form_for review do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if params[:book_id].present? %>
    <h3 class="title-font">
      <%= t "user.write_review" %> for 
      <span style="color: red">
        <%= link_to book.title, book_path(book) %>
      </span>
    </h3><br>
  <% else %>
    <h2 class="text-left"><%= t ".form_title" %></h2><br>
  <% end %>
  <div class="form-group pmd-textfield">
    <%= form.label :title, class: "control-label" %> <span style="color: red;">*</span><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group pmd-textfield">
    <% if params[:book_id].present? %>
      <%= form.hidden_field :book_id, value: params[:book_id] %>
    <% else %>
      <label class="control-label">
        <%= t ".book_name" %>
        <span style="color: red;">*</span>
      </label>
      <%= form.select :book_id, support.load_books,
        {include_blank: t(".choose_book")}, {class: "select-with-search
        form-control pmd-select2 select-book required"} %>
    <% end %>
  </div>
  
  <div class="form-group pmd-textfield">
    <%= form.label :content, class: "control-label" %><br>
    <%= form.text_area :content, class: "ckeditor" %>
  </div>
  
  <div class="text-center">
    <div class="actions">
      <%= form.submit class:"btn btn-info" %>
    </div>
    
    <%= link_to 'Back', reviews_path, class:"btn btn-default" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="write-review">
  <%= render 'form', review: @review, book: @support.find_book,
    support: @support %>
</div>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="write-review">
  <%= render 'form', review: @review, book: @support.find_book,
    support: @support %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>
<% book = @review.book %>
<div class="review-details">
  <div class="row">
    <div class="row">
      <div id="imagecol" class="col-sm-4">
        <div class="bookCoverContainer">
          <div class="bookCoverPrimary">
            <%= link_to book_path(book) do %>
              <img id="coverImage" alt="<%= book.title %>"
                src="<%= book.picture %>">
            <% end %>
          </div>
          <p class="user-rate">Rate this book:</p>
          <% if user_signed_in? %>
            <input type="hidden" id="is_rate" value="<%= rate(book).present? %>">
            <div class="hidden current-book-id" id="<%= book.id %>"></div>
            <div id="rate">
              <% (1..(load_rate author_rate(book, current_user)).first).each do |s| %>
                <img src="/assets/star-on" class="rate">
              <% end  %>
              <% (1..(load_rate author_rate(book, current_user)).second).each do |s| %>
                <img src="/assets/star-half" class="rate">
              <% end  %>
              <% (1..(load_rate author_rate(book, current_user)).last).each do |s| %>
                <img src="/assets/star-off" class="rate">
              <% end %>
            </div>
          <% else %>
            <%= link_to "Login", user_session_path %> to rate
          <% end %>
        </div>
      </div>
      
      <div class="last col-sm-8" id="metacol">
        <h1 id="bookTitle" class="bookTitle">
          <%= link_to book.title, book_path(book) %>
        </h1>
        <div id="bookAuthors" class="stacked">
          <span class="by smallText">
            <% if book.authors.any? %>
              <small>by</small> 
              <% book.authors.each do |author| %>
                <span><%= author.name %></span>
                <% unless author == book.authors.last %>,<% end %>
              <% end %>
            <% end %>
          </span>
        </div>
        <div class="uitext stacked average">
          <span class="average-rate" data-score="<%= book.average_rate %>"></span>
          <%= book.average_rate.round(2) %>
          <span class="bullet time-ago-bullet" aria-hidden="true">&nbsp;•&nbsp;</span>
          <%= book.rates.count %> Ratings
          <span class="bullet time-ago-bullet" aria-hidden="true">&nbsp;•&nbsp;</span>
          <span class="count value-title" title="7171">
            <%= book.reviews.count %>
          </span>
          Reviews
        </div>
        
        <div id="descriptionContainer">
          <div id="description" class="readable stacked" style="right:0">
            <span><%= book.description %></span>
          </div>
        </div>
        
        <div id="details" class="uitext darkGreyText">
          <div class="">
            Published <%= book.publish_date.strftime("%d %b %Y") %>
            by <b><%= book.publisher %></b>
          </div>
        </div>
      </div>

    </div>
  </div>
  <br><br>
  
  <div id="comments">
    <div class="review row post-content">
      <% review = @review %>
      <div class="col-sm-1">
        <%= link_to user_path(review.user), class:"avatar" do %>
          <img alt="<%= review.user.name %>" src="<%= review.user.image %>"
            title="<%= review.user.name %>">
        <% end %>
      </div>
  
      <div class="col-sm-11">
        <div class="reviewHeader uitext stacked">
          <span class="reviewDate createdAt right text-right">
            <%= review.created_at.strftime("%d %b %Y") %>
          </span>
          <span class="reviewUser">
            <%= link_to review.user.name, user_path(review.user),
              class: "user" %>
            <span class="user">rated it</span>
            <span class="average-rate" data-score="<%= author_rate(book, review.user) %>"></span>
          </span>
          
          <b><p><%= review.title %></p></b>
        </div>
      </div>

      <div class="reviewText stacked col-sm-12">
        <p class="readable">
          <span><%= review.content %></span>
        </p>
        
        <% if user_signed_in? && (current_user == @review.user) %>
          <%= link_to 'Edit', edit_review_path(@review), class:"btn btn-success" %>
          <%= link_to 'Delete', review_path(@review), method: :delete,
            class:"btn btn-danger" %>
        <% end %>
      </div>
    </div>
  
    <input type="hidden" id="review-id" value="<%= @review.id %>">
    <% if user_signed_in? %>
      <span class="like">
        <% if like(@review).present? %>
          <span class="btn icon-btn btn-info unlikeBtn
            pmd-ripple-effect pmd-btn-raised"
            data="<%= @review.id %>" like-id="<%= like(@review).id %>">
            <i class="fa fa-thumbs-up"></i>
            Liked
          </span>&nbsp;
          <% if @review.likes.size > 0 %>
            <span class="like-counter like-count-<%= @review.id %>">
              <%= @review.likes.size %>
            </span> like(s)
          <% else %>
            Be the first to like.
          <% end %>
        <% else %>
          <span class="btn icon-btn btn-default likeBtn
            pmd-ripple-effect pmd-btn-raised"
            data="<%= @review.id %>">
            <i class="fa fa-thumbs-o-up"></i>
            <span>Like it</span>
          </span>&nbsp;
            <% if @review.likes.size > 0 %>
            <span class="like-counter like-count-<%= @review.id %>">
              <%= @review.likes.size %>
            </span> like(s)
          <% else %>
            Be the first to like.
          <% end %>
        <% end %>
      </span>
    <% else %>
      <span class="like-login">
        <span class="btn icon-btn pmd-ripple-effect
          pmd-btn-raised loginBtn">
          <i class="fa fa-thumbs-o-up"></i>
          <span>Like</span>
        </span>&nbsp;
        <% if @review.likes.size > 0 %>
          <span class="like-counter like-count-<%= @review.id %>">
            <%= @review.likes.size %>
          </span> like(s)
        <% else %>
          Be the first to like.
        <% end %>
      </span>
    <% end %><br><br>

  
    <h2>Comments</h2><hr>
    <% if user_signed_in? %>
      <%= render "comments/form", review: @review,
        comment: @support.new_comment %>
      <div id="comments" class="comments-part">
        <%= render "comments/comments", review: @review,
          comments: @support.comments %>
      </div>
    <% else %>
      <h3>
        <%= link_to t("user.login"), user_session_path,
        data: {turbolinks: false} %>
        <%= t ".to_comment" %>
      </h3><br>
      <div id="comments" class="comments-part">
        <%= render "comments/comments", review: @review,
          comments: @support.comments %>
      </div>
    <% end %>
  </div>
</div>