config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: :registrations }
  
  root "static_pages#show"
  
  resources :users, only: [:index, :show] do
    resources :reviews, except: :index
  end
  resources :books, only: [:index, :show] do
    resources :rates, only: [:create]
    resource :suggest_books, only: :create
  end
  resources :reviews do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :authors, only: [:index, :show]
  resources :categories, only: [:show]
  resources :comments
  get "users/:id/reviews" => "users#reviews", as: :user_all_reviews
  resources :relationships, only: [:create, :destroy]
  get "search", to: "static_pages#index", as: :search
  get "users/:id/followers", to: "users#followers", as: :user_followers
  get "users/:id/following", to: "users#following", as: :user_following
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :author_books
  has_many :books, through: :author_books
  
  validates :name, presence: true
  
  mount_uploader :image, AvatarUploader
end

app/models/author_book.rb
class AuthorBook < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  attr_accessor :average_rate
  
  has_many :author_books
  has_many :authors, through: :author_books, dependent: :destroy
  has_many :book_categories
  has_many :categories, through: :book_categories, dependent: :destroy
  has_many :rates
  has_many :reviews

  validates :title, presence: true
  
  mount_uploader :picture, ImagesUploader
  
  ransack_alias :book, :title_or_isbn_or_authors_name
  
  def average_rate
    book = Book.find_by id: self.id
    rates = book.rates
    size = rates.size
    total = 0
    rates.each do |rate|
      total += rate.score
    end
    return total * 1.0 / size if size > 0
    0
  end
  
  private
  def self.ransortable_attributes(auth_object = nil)
    %w(title isbn) + _ransackers.keys
  end
end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :book
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :book_categories
  has_many :books, through: :book_categories, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :review

  mount_uploader :url, ImagesUploader, allow_destroy: true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  has_many :photos
  has_many :comments, dependent: :destroy
  has_many :likes

  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :title, presence: true
  
  def count_like
    review = Review.find_by id: self.id
    likes = review.likes
    size = likes.size
    return size
  end
end

app/models/suggest_book.rb
class SuggestBook < ApplicationRecord
  belongs_to :book

  class << self
    def create_suggest_book suggest_books_params, book, from_id
      ActiveRecord::Base.transaction do
        to_ids = suggest_books_params[:to_id].reject &:blank?
        @suggest_books = []
        to_ids.each do |to_id|
          @suggest_book = SuggestBook.create! book_id: book.id,
            from_id: from_id, to_id: to_id,
            content: suggest_books_params[:content]
          @suggest_books.push @suggest_book
        end
      end
      return @suggest_books if @suggest_book.save
      nil
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]
  
  has_many :reviews
  has_many :comments, dependent: :destroy
  has_many :rates
  
  validate :validate_username
  validates :name, presence: true

  mount_uploader :image, AvatarUploader
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
  
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
  # tinh tong so like user nhan duoc
  def count_getted_like
    user = User.find_by id: self.id
    reviews = user.reviews
    total = 0
    reviews.each do |review|
      total += review.count_like
    end
    return total
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
      @books = Book.all
    end
    def show
      @book = Book.find(params[:id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_review, only: [:create, :destroy]
  before_action :find_like, only: :destroy

  def create
    likes = @review.likes
    like = likes.create user_id: current_user.id

    render json: {likes_count: likes.size, like_id: like.id}
  end

  def destroy
    @like.destroy
    render json: {likes_count: @review.likes.size}
  end

  private
  def find_review
    @review = Review.find_by id: params[:review_id]
  end

  def find_like
    @like = Like.find_by id: params[:id]
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_book, only: [:create]

  def create
    rate =  if @book
      @book.rates.new rate_params
    else
      Rate.new rate_params
    end
    rate.user_id = current_user.id
    rate.save
  end

  private
  def find_book
    @book = Book.find_by id: params[:book_id]
    @rate = @book.rates.find_by user_id: current_user.id

    @rate.destroy if @rate
  end

  def rate_params
    params.require(:rate).permit :score
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "app_name"
    page_title.empty? ? base_title : "#{page_title} - #{base_title}"
  end
  
  def like review
    review.likes.find_by user_id: current_user.id
  end
  
  def author_rate(book, user)
    rates = book.rates.where(user_id: user.id)
    size = rates.size
    total = 0
    rates.each do |rate|
      total += rate.score
    end
    return total * 1.0 / size if size > 0
    0
  end

  def rate movie
    movie.rates.find_by user_id: current_user.id
  end

end

app/helpers/books_helper.rb
module BooksHelper
  def load_rate rate
    if rate
      remain = rate % 1
      rate_int = rate.to_i
      unrated = 5 - rate_int
      unrated_half = unrated - 1
      if remain < 0.25
        [rate_int, 0, unrated]
      elsif remain < 0.75
        [rate_int, 1, unrated_half]
      else
        [rate_int + 1, 0, unrated_half]
      end
    else
      [0, 0, 5]
    end
  end
  
  def author_rate(book, user)
    rates = book.rates.where(user_id: user.id)
    size = rates.size
    total = 0
    rates.each do |rate|
      total += rate.score
    end
    return total * 1.0 / size if size > 0
    0
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer_resize">
    <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
    <div class="clr"></div>
  </div>
  <div class="clr"></div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand"><%= t "home.title" %></span>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to root_path, data: {turbolinks: false} do %>
          <%= t "user.home" %>
        <% end %>
      </li>
      <!--<li class="dropdown pmd-dropdown">-->
      <!--  <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
      <!--    Category-->
      <!--    <span class="caret"></span>-->
      <!--  </a>-->
      <!--  <ul class="dropdown-menu">-->
      <!--    < Category.order("title asc").each do |cate| %>-->
      <!--      <div class="">-->
      <!--        <li>-->
      <!--          <= link_to t(cate.title), category_path(cate),-->
      <!--            data: {turbolinks: false} %>-->
      <!--        </li>-->
      <!--      </div>-->
      <!--    < end %>-->
      <!--  </ul>-->
      <!--</li>-->
      <li>
        <%= link_to "#", data: {turbolinks: false} do %>
          <!--<i class="fa fa-users fa-md " aria-hidden="true"></i>-->
          <%= t "home.about" %>
        <% end %>
      </li>
      <li>
        <%= link_to "#", data: {turbolinks: false} do %>
          <!--<span class="glyphicon glyphicon-envelope"></span>-->
          <%= t "home.contact" %>
        <% end %>
      </li>
    </ul>
    
    <%= form_tag search_path, method: :get, class:"navbar-form navbar-left" do %>
      <div class="form-group">
        <%= text_field_tag :q, params[:q], class:"form-control",
          placeholder:"Title / ISBN / Author" %>
      </div>
      <%= button_tag(class: "button btn btn-default") do  %>
        <i class="glyphicon glyphicon-search"></i>
      <% end %>
    <% end %>
      
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <%= render "layouts/header_user.html.erb" %>
      <% else %>
        <li>
          <%= link_to new_user_registration_path, method: :get, data: {turbolinks: false} do %>
            <span class="glyphicon glyphicon-user"></span> <%= t "user.sign_up" %>
          <% end %>
        </li>
        <li>
          <%= link_to user_session_path, method: :get, data: {turbolinks: false} do %>
            <span class="glyphicon glyphicon-log-in"></span> <%= t "user.login" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_header0.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <%= link_to "Fukurou Toshokan", root_path, class: "nav-link" %>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Contact</a>
    </li>
    <li class="nav-item">
      <form class="form-inline" action="/action_page.php">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-success" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </form>
    </li>

    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user), class:"nav-link dropdown-toggle", id:"navbardrop", "data-toggle": "dropdown" do %>
          <%= current_user.username %>
        <% end %>
        
        <div class="dropdown-menu">
          <%= link_to user_path(current_user), class:"dropdown-item" do %>
            My profile
          <% end %>
          <a class="dropdown-item" href="#">My reviews</a>
          <%= link_to "Signout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/_header_user.html.erb
<li>
  <%= link_to new_review_path, class: "dropbtn", data: {turbolinks: false} do %>
    <i class="fa fa-pencil-square-o fa-md" aria-hidden="true"></i>
    <%= t "user.write_review" %>
  <% end %>
</li>

<li class="dropdown pmd-dropdown">
  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-user" aria-hidden="true"></i>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu dropdown-menu-right">
    <li>
      <%= link_to user_path(current_user), class:"blog-list-item-anchor",
        data: {turbolinks: false} do %>
        <span class="blog-list-item-avatar">
          <%-#<%= image_tag current_user.image, class:"blog-list-item-image" %>
        </span>
        <span class="blog-list-item-info">
          <span class="blog-list-item-info-name">
            <%= current_user.name %>
          </span>
        </span>
      <% end %>
    </li>
    <li role="separator" class="divider"></li>
    <li>
      <% if current_user.is_admin? %>
        <%= link_to t("layouts.header.admin"), rails_admin_path,
          data: {turbolinks: false},
          style: "font-weight: bold", class: "admin-btn" %>
      <% end %>
    </li>
    <li>
      <%= link_to user_all_reviews_path(current_user), class:"blog-sub-nav-item-link",
        data: {turbolinks: false} do %>
        <%= t "user.reviews" %>
      <% end %>
    </li>
    <li>
      <%= link_to edit_user_registration_path, method: :get,
        data: {turbolinks: false} do %>
        <i class="fa fa-cog" aria-hidden="true"></i> <%= t "user.settings" %>
      <% end %>
    </li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete,
        data: {turbolinks: false} do %>
        <i class="fa fa-sign-out" aria-hidden="true"></i> <%= t "user.sign_out" %>
      <% end %>
    </li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="content-web">
    <%= render "layouts/header" %>

    <div class="wrapper">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>